config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  
  get '/login' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :cards, :only => [:index, :show]
  get '/cards/index_type/:type' => 'cards#index_type', :as => 'cards_index_type'

  get '/auth/google_oauth2/callback' => 'sessions#create'
  get '/auth/failure' => 'welcome#home'
  
  resources :users, :only => [:new, :show, :edit, :create, :update]

  resources :users do
    resources :accounts
  end
   
 namespace 'admin' do
    resources :accounts 
    resources :cards
    resources :bank_partners
  end

  resources :accounts
  get '/users/:user_id/cards/:card_id/accounts/new' => 'accounts#new', :as =>'new_user_account_with_card'

  resources :categories
  resources :card_bank_partners
  resources :bank_partners, :only => [:show, :index]
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
    
	has_many :accounts
	has_many :cards, :through => :accounts
	has_secure_password

    validates :email, :presence => true, :uniqueness => true
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
    validates :name, :presence => true
    validates :password, :length => { :minimum => 7 }
    validates :password, :confirmation => true

    def self.find_or_create_by_omniauth(auth_hash)
    	self.where(:email => auth_hash[:info][:email]).first_or_create do |user|
    		user.uid = auth_hash[:uid]
    		user.name = auth_hash[:info][:name]
    		user.email = auth_hash[:info][:email]
    		user.image = auth_hash[:info][:image]
            
    		random_password = Random.new_seed
    		user.password = random_password.to_s
    		user.password_confirmation = random_password.to_s
    	end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, :except => [:new, :create]
    before_action :owner_access 
	#GET 
	def new
		@user = User.new
	end

	def show
		@user = User.find_by(id: params[:id])
	end
    
    def edit
    	@user = User.find_by(id: params[:id])
    end

    #POST
	def create
		@user = User.create(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, :alert => "successfuly created user"
		else
			render :new
		end
	end

	def update
		@user = User.find_by(id: params[:id])
		@user.update(user_params)
		if @user.save
			redirect_to root_path
		else
			render :edit
		end
	end
    
	private 
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def method_name
		
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="user_form form">
<%= form_for user do |user_builder|%>
<%= render "shared/error_messages", :target => user %>

 <div class="field">
	 <p>
	 	<%= user_builder.label :name%>
	 	<%= user_builder.text_field :name%>
	 </p>
 </div>

 <div class="field">
	 <p>
	 	<%= user_builder.label :email%>
	 	<%= user_builder.email_field :email%>
	 </p>
 </div>

 <div class="field">
	 <p>
	 	<%= user_builder.label :password%>
	 	<%= user_builder.password_field :password%>
	 </p>
 </div>

 <div class="field">
	 <p>
	 	<%= user_builder.label :password_confirmation%>
	 	<%= user_builder.password_field :password_confirmation%>
	 </p>
 </div>

 <%= user_builder.submit %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Your Information</h1>
<%= render :partial => 'form', :locals => {:user => @user }%>

app/views/users/new.html.erb
<h1>Create User</h1>
<%= render :partial => 'form', :locals => {:user => @user }%>

app/views/users/show.html.erb
<%= link_to "Edit Your Inforamtion", edit_user_path(@user.id) %> | 
<%= link_to("Create New Account", new_user_account_path(@user.id))%>
<h4>Your Cards</h4>
<%= render :partial => 'accounts/accounts', :locals => { :accounts => @user.accounts, :user => @user}%>