config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  
  get '/login' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :cards, :only => [:index, :show]
  get '/cards/index_type/:type' => 'cards#index_type', :as => 'cards_index_type'

  get '/auth/google_oauth2/callback' => 'sessions#create'
  get '/auth/failure' => 'welcome#home'
  
  resources :users, :only => [:new, :show, :edit, :create, :update]

  resources :users do
    resources :accounts
  end
   
 namespace 'admin' do
    resources :accounts 
    resources :cards
    resources :bank_partners
  end

  resources :accounts
  get '/users/:user_id/cards/:card_id/accounts/new' => 'accounts#new', :as =>'new_user_account_with_card'

  resources :categories
  resources :card_bank_partners
  resources :bank_partners, :only => [:show, :index]
  
  

end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :card_bank_partners
	has_many :bank_partners, through: :card_bank_partners
	belongs_to :category
    
    # accepts_nested_attributes_for :bank_partners
    
    enum :c_type => [:personal, :business]

    validates :name, :uniqueness => true
    NON_VALIDATABLE_ATTR = ["id", "created_at", "updated_at"]
	VALIDATABLE_ATTR = self.attribute_names.reject{|attr| NON_VALIDATABLE_ATTR.include?(attr)}
	validates_presence_of VALIDATABLE_ATTR
    

    def bank_partners_attributes=(bank_partners_attributes)
		bank_partners_attributes.each do |i, attributes|
            if attributes[:name].present?
                bank_partner = BankPartner.find_or_create_by(:name => attributes[:name])
                if !self.bank_partners.include?(bank_partner)
                    self.bank_partners << bank_partner
                end
            end
		end
    end

	def self.type(c_type)
		Card.all.find_all do |card|
			card.c_type == c_type
		end
	end

end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < ApplicationController
    before_action :admin_access
    before_action :find_card, :only => [:edit, :update, :show, :destroy] 
	#GET
	def index
        @cards = Card.all
	end

	def new
		@card = Card.new
        render "admin/cards/new.html.erb", :layout => false 
	end

	def edit
	end
    
    def show
    end

    #POST
    def create
        @card = Card.create(card_params.reject{|a| a == 'c_type'})
        @card.c_type = card_params[:c_type].to_i
        if @card.save
            respond_to do|format| 
                format.html { redirect_to admin_card_path(@card.id), alert: 'Card successfully created' }
                format.json { render :json => @card, :status => 201 }
            end    
        else
            render :new
        end	
    end

    def update
        @card.update(card_params.reject{|a| a == 'c_type'})
        @card.c_type = card_params[:c_type].to_i
        if @card.save
            redirect_to admin_card_path(@card.id), alert: 'Card successfully edited'
        else
            render :edit
        end
    end

    def destroy 
        card = @card.delete
        redirect_to admin_cards_path, :alert => "Succssesfuly removed #{card.name}"	
    end

    private

    def find_card
    	@card = Card.find_by(:id => params[:id])
    end

    def card_params
        params.require(:card).permit(:name, 
                                    :credit_needed, 
                                    :c_type, 
                                    :bonus, 
                                    :apr, 
                                    :balance_transfer_apr, 
                                    :balance_transfer_period, 
                                    :anual_fee, 
                                    :corp_url, 
                                    :category_id,
                                    :bank_partner_ids => [], 
                                    :bank_partners_attributes => [:name]
                                    )
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	#GET
	def index
		@cards = Card.all
		respond_to do |format|
		    format.html { @cards } 
		    format.json { render :json => @cards }   
		end  
	end
    
	def index_type
	    @cards = Card.type(params[:type])
	    render 'index' 
	end

	def show
		@card = Card.find_by(:id => params[:id])
		respond_to do |format|
			format.html { @card }
			format.json { render :json => @card }
		end 	
	end

end

app/helpers/cards_helper.rb
module CardsHelper
	def links_for_bank_partners(card)
      links = card.bank_partners.map do |bank| 
      	        link_to(bank.name, bank_partner_path(bank.id)) 
              end
      links.join(" | ").html_safe        
	end

	def admin_create_card
		if current_user.try(:admin) 
			link_to("Create New Card", new_admin_card_path, id: "admin_creat_new_card")
		end
	end
end	

app/views/cards/_card.html.erb
<div class="indevidual_card">
	<p><strong>name:</strong><%= link_to(card.name, card.corp_url) %></p><br> 
	<p><strong>type:</strong> <%= link_to(card.c_type, cards_index_type_path(card.c_type)) %></p><br>
	<p><strong>bonus:</strong> <%= card.bonus %></p><br>
	<p><strong>apr:</strong> <%= card.apr %></p><br>
	<p><strong>anual fee:</strong> <%= card.anual_fee %></p><br>
	<p><strong>credit needed:</strong> <%= card.credit_needed %></p><br>
	<p><strong>balance transfer apr:</strong> <%= card.balance_transfer_apr %></p><br>
	<p><strong>balance transfer:</strong> <%= card.balance_transfer_period %></p><br>
	<p><strong>category:</strong> <%= link_to(card.category.title, category_path(card.category.id)) %></p><br>
	<p><strong>banks:</strong> <%= links_for_bank_partners(card) %></p><br>
	<%= admin_buttons_for(card) %>
</div>

app/views/cards/_cards.html.erb
<div class="cards_list">
	<ul>
	    <% cards.each do |card|%>
		<li>
			<div class="container-fluid info floated card">
			<%= link_to(card.name, card_path(card.id), data: { id: "#{card.id}" }, class: "card_name")%> | 
			<%= link_to(card.c_type, cards_index_type_path(card.c_type)) %><br>
			<strong>Bonus: </strong><%= card.bonus %> 
			<%= admin_buttons_for(card) %> 
			<%= add_card(card)%>
			</div>
		</li> 
	    <% end %>
	</ul>
</div>

app/views/cards/index.html.erb
<h1>Cards</h1>
<%= render :partial => 'cards', :locals => { :cards => @cards } %>

app/views/cards/show.html.erb
<h1>Card Info</h1>
<%= render :partial => 'card', :locals => {:card => @card} %>