config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  
  get '/login' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :cards, :only => [:index, :show]
  get '/cards/index_type/:type' => 'cards#index_type', :as => 'cards_index_type'

  get '/auth/google_oauth2/callback' => 'sessions#create'
  get '/auth/failure' => 'welcome#home'
  
  resources :users, :only => [:new, :show, :edit, :create, :update]

  resources :users do
    resources :accounts
  end
   
 namespace 'admin' do
    resources :accounts 
    resources :cards
    resources :bank_partners
  end

  resources :accounts
  get '/users/:user_id/cards/:card_id/accounts/new' => 'accounts#new', :as =>'new_user_account_with_card'

  resources :categories
  resources :card_bank_partners
  resources :bank_partners, :only => [:show, :index]
  
  

end

app/views/layouts/_admin.html.erb
<div class="admin_section">
 <h4>Admin Mode</h4>
 <%= admin_create_bank_partner %> | <%= admin_create_card %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"/>Home</a>
    </div>
    
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
       <% if logged_in? %>
        <li><%= link_to("Cards", cards_path) %></li>
        <li><%= link_to("Bank Partners", bank_partners_path) %></li>
        <li><%= link_to("Hello, #{current_user.name}!", user_path(current_user.id))%></li>
       <% else %>
        <li><%= link_to("Cards", cards_path) %></li>
       <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
        <% if logged_in? %>
         <li>
            <%= link_to logout_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> Logout
            <% end %> 
         </li>
        <% else %>
          <li>
            <%= link_to login_path do %>
              <span class="glyphicon glyphicon-log-in"></span> Login
            <% end %>   
          </li>
          <li>
              <%= link_to new_user_path do%>
                <span class="glyphicon glyphicon-user"></span> Sign Up
              <% end %>
          </li>
          <li><%= link_to("Login With Google", '/auth/google_oauth2')%></li>
        <% end %>
      </ul>
    </div>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreditCardsManagment</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>

    <%= render 'layouts/header'%>

    <div id="main_page" class="container"  role="main">
        <%= render 'layouts/admin' if current_user.try(:admin)%>
    	<% flash.each do |name, msg| %>
    	<%= content_tag :div, msg, class: name %>
    	<% end %>
    	
      <%= yield %>
    </div>

    <script id="cardModalTemplate" type="text/x-handlebars-template" >
      <div class="modal" id="modalCard{{id}}">
        <div class="card-content">
          <a href="/cards"><span class="close">&times;</span></a>
          <h1>{{name}}</h1>
          <div class="body">
            Card Type:<strong> {{c_type}}</strong><br>
            Bonus: <strong> {{bonus}}</strong><br>
            APR: <strong> {{apr}}</strong><br>
            Anual Fee: <strong> ${{anual_fee}}</strong><br>
            Credit Needed: <strong> {{credit_needed}}</strong><br>
            Balance Transfar APR: <strong> {{balance_transfer_apr}}%</strong><br>
            Balance Transfer Period: <strong> {{balance_transfer_period}} Months</strong><br>
            Category: <strong>{{category}}</strong><br>
            Bank Partners:  <strong>
                              {{#each bank_partners}}
                                    {{name}}, 
                                {{/each}}
                            </strong><br>
            <a href="{{corp_url}}"> {{corp_url}}</a>
          </div>
        </div>
      </div>
    </script>


    <script id="bankPartnerModalTemplate" type="text/x-handlebars-template">
      <div class="modal">
        <div class="cards-content-ul">
          <span class="close" onclick="closeModal(this)">&times;</span>
          <h1>{{name}}</h1>
          <div class="body">
            <ul>
              {{#each cards}}
                <li>
                  <div>
                    <a data-id="7" class="card_name" href="/cards/{{id}}">{{name}}</a> | 
                    <a href="/cards/index_type/{{c_type}}">{{c_type}}</a><br>
                    Bonus: <strong>{{bonus}}</strong><br>
                    URL: <strong><a href="{{corp_url}}">{{corp_url}}</a></strong>     
                  </div><br>
                </li>
              {{/each}}  
            </ul>
          </div>    
        </div>
      </div>  
    </script>

    <div class="modal" id="newCardForm">
      <div class="card-form-content">
        <span class="close" onclick="closeModal(this)">&times;</span>
      </div>
    </div>


  </body>
</html>